apiVersion: v2
name: domain-server
description: The Domain Server is responsible for storing poses of portals in domains and spatial domain data such as scene reconstructions and occupancy maps.
type: application
version: 0.5.2
appVersion: "0.6"
maintainers:
  - name: dataviruset
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: juicefs-s3-gateway
    version: 0.11.3
    repository: https://juicedata.github.io/charts/
    condition: juicefs-s3-gateway.enabled
