apiVersion: v2
name: reconstruction-server
description: The Reconstruction Server runs local and global refinement pipelines for scene reconstruction, pose refinement and more.
type: application
version: 0.2.0
appVersion: "0.2.0"
maintainers:
  - name: dataviruset
