{{- if .Values.monitoring.podMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "splatter-server.fullname" . }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "splatter-server.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "splatter-server.fullname" . }}
  selector:
    matchLabels:
      {{ include "splatter-server.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - interval: {{ .Values.monitoring.podMonitor.scrapeInterval }}
      path: /metrics
      port: admin
{{- end }}
